#!/bin/bash
set -e

# Deploy contracts to local node in dependency order
# Starts node, deploys contracts, keeps node running

ADDRESSES_FILE="target/.addresses"
NODE_URL="${NODE_URL:-ws://127.0.0.1:9944}"
SURI="${SURI:-//Alice}"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=========================================="
echo "  Local Deployment Script"
echo -e "==========================================${NC}"

# Check if node is already running
if curl -s -o /dev/null -w '' --connect-timeout 1 http://127.0.0.1:9944 2>/dev/null; then
    echo -e "${YELLOW}Node already running at $NODE_URL${NC}"
else
    echo -e "${YELLOW}Starting local ink! node...${NC}"
    pop up ink-node -y -d
    echo "Waiting for node to be ready..."
    sleep 3
fi

# Clear previous addresses
echo "# Deployed contract addresses" > "$ADDRESSES_FILE"
echo "# Generated by deploy-local.sh on $(date)" >> "$ADDRESSES_FILE"
echo "" >> "$ADDRESSES_FILE"

# Helper function to deploy a contract and extract its address
# Usage: deploy_contract <name> <path> <address_key> [constructor_args...]
deploy_contract() {
    local name=$1
    local path=$2
    local address_key=$3
    shift 3
    local args=("$@")

    echo ""
    echo -e "${BLUE}=== Deploying $name ===${NC}"

    # Build first
    echo "Building $name..."
    pop build "$path" 2>&1 | grep -E "(Building|Compiling|Finished|Build completed)" || true

    # Get the contract file path (based on crate name from Cargo.toml)
    local crate_name=$(grep -m1 '^name' "$path/Cargo.toml" | sed 's/.*= *"\([^"]*\)".*/\1/')
    local contract_file="target/ink/$crate_name/$crate_name.contract"

    if [ ! -f "$contract_file" ]; then
        echo "ERROR: Contract file not found at $contract_file"
        exit 1
    fi

    # Build the instantiate command
    local cmd="cargo contract instantiate $contract_file -s $SURI --url $NODE_URL -x -y --output-json"

    # Add constructor args if provided
    if [ ${#args[@]} -gt 0 ]; then
        cmd="$cmd --args ${args[*]}"
    fi

    # Deploy and capture JSON output
    echo "Deploying to $NODE_URL..."
    local result=$(eval "$cmd" 2>&1)

    # Extract address from JSON output
    local address=$(echo "$result" | jq -r '.contract // empty' 2>/dev/null)

    if [ -z "$address" ]; then
        echo "ERROR: Failed to extract address for $name"
        echo "Output was:"
        echo "$result"
        exit 1
    fi

    echo "$address_key=$address" >> "$ADDRESSES_FILE"
    echo -e "${GREEN}✓ $address_key=$address${NC}"
}

echo ""
echo -e "${YELLOW}--- Phase 1: Registries (no dependencies) ---${NC}"
deploy_contract "ContextRegistry" "src/systems/registries/contexts" "CONTEXT_REGISTRY"
deploy_contract "ContractRegistry" "src/systems/registries/contracts" "CONTRACT_REGISTRY"

echo ""
echo -e "${YELLOW}--- Phase 2: Systems (depend on registries) ---${NC}"
deploy_contract "Reputation" "src/systems/reputation" "REPUTATION"
deploy_contract "Disputes" "src/systems/disputes" "DISPUTES"

echo ""
echo -e "${YELLOW}--- Phase 3: Examples ---${NC}"
# The example contracts take a context_id (32 bytes) as constructor argument
# Using simple hex strings padded to 32 bytes

# Reputation example context
REPUTATION_CONTEXT_ID="0x4558414d504c455f434f4e5445585400000000000000000000000000000000"
deploy_contract "ReputationContextOwner" "examples/reputation-interaction/contract" "REPUTATION_CONTEXT_OWNER" "$REPUTATION_CONTEXT_ID"

# Item tracker example context
ITEM_TRACKER_CONTEXT_ID="0x4954454d5f545241434b45525f435458000000000000000000000000000000"
deploy_contract "ItemTracker" "examples/system-basic/contract" "ITEM_TRACKER" "$ITEM_TRACKER_CONTEXT_ID"

# Update TypeScript descriptors for reputation-interaction
echo ""
echo -e "${YELLOW}--- Updating TypeScript descriptors ---${NC}"
cd examples/reputation-interaction
pnpm papi ink add ../../target/ink/contexts/contexts.contract 2>&1 | grep -v "^$" | head -3 || true
pnpm papi ink add ../../target/ink/reputation/reputation.contract 2>&1 | grep -v "^$" | head -3 || true
pnpm papi ink add ../../target/ink/reputation_context_owner/reputation_context_owner.contract 2>&1 | grep -v "^$" | head -3 || true
cd ../..

# Update TypeScript descriptors for system-basic
cd examples/system-basic/ui
pnpm install 2>&1 | tail -3 || true
pnpm papi ink add ../../../target/ink/item_tracker/item_tracker.contract 2>&1 | grep -v "^$" | head -3 || true
cd ../../..

echo ""
echo -e "${GREEN}=========================================="
echo "  Deployment complete!"
echo -e "==========================================${NC}"
echo ""
echo "Addresses written to $ADDRESSES_FILE:"
cat "$ADDRESSES_FILE"
echo ""
echo -e "${BLUE}Node running at: $NODE_URL${NC}"
echo -e "${BLUE}Portal: https://polkadot.js.org/apps/?rpc=ws://localhost:9944/#/explorer${NC}"
echo ""
echo -e "${YELLOW}To verify deployment:${NC}"
echo "  cd examples/reputation-interaction && bun src/verify-local.ts"
echo ""
echo -e "${YELLOW}To stop the node:${NC}"
echo "  pkill -f 'ink-node'"
